from serialization.enum_json import EnumByValueJson


class ItemType(EnumByValueJson):
    MODULE = "module"
    ITEM_WITH_TAGS = "item-with-tags"
    DECONSTRUCTION_ITEM = "deconstruction-item"
    ARMOR = "armor"
    SPIDERTRON_REMOTE = "spidertron-remote"
    ITEM_WITH_INVENTORY = "item-with-inventory"
    COPY_PASTE_TOOL = "copy-paste-tool"
    BLUEPRINT = "blueprint"
    TOOL = "tool"
    CAPSULE = "capsule"
    BLUEPRINT_BOOK = "blueprint-book"
    REPAIR_TOOL = "repair-tool"
    UPGRADE_ITEM = "upgrade-item"
    AMMO = "ammo"
    ITEM_WITH_LABEL = "item-with-label"
    RAIL_PLANNER = "rail-planner"
    MINING_TOOL = "mining-tool"
    ITEM = "item"
    FLUID = "fluid"
    SELECTION_TOOL = "selection-tool"
    GUN = "gun"
    ITEM_WITH_ENTITY_DATA = "item-with-entity-data"
