from serialization.enum_json import EnumByValueJson
from serialization.enum_mapping_json import EnumMappingJson


class Category(EnumByValueJson):
    NO_CATEGORY = "no-category"
    SPACE_GROWTH = "space-growth"
    SPACE_SUPERCOMPUTING_2 = "space-supercomputing-2"
    SPACE_LASER = "space-laser"
    SPACE_OBSERVATION_VISIBLE = "space-observation-visible"
    SPACE_OBSERVATION_MICROWAVE = "space-observation-microwave"
    SPACE_HYPERCOOLING = "space-hypercooling"
    PULVERISING = "pulverising"
    SPACE_OBSERVATION_XRAY = "space-observation-xray"
    DUMMY = "dummy"
    SPACE_MATERIALISATION = "space-materialisation"
    FIXED_RECIPE = "fixed-recipe"
    PRESSURE_WASHING = "pressure-washing"
    CORE_FRAGMENT_PROCESSING = "core-fragment-processing"
    LIFESUPPORT = "lifesupport"
    SPACE_SUPERCOMPUTING_1 = "space-supercomputing-1"
    SPACE_RADIATION = "space-radiation"
    SPACE_ASTROMETRICS = "space-astrometrics"
    SPACE_OBSERVATION_GAMMARAY = "space-observation-gammaray"
    CRAFTING_WITH_FLUID = "crafting-with-fluid"
    SPACE_PLASMA = "space-plasma"
    SPACE_OBSERVATION_INFRARED = "space-observation-infrared"
    OIL_PROCESSING = "oil-processing"
    DELIVERY_CANNON_WEAPON = "delivery-cannon-weapon"
    SPACE_MANUFACTURING = "space-manufacturing"
    SPACE_BIOCHEMICAL = "space-biochemical"
    ADVANCED_CRAFTING = "advanced-crafting"
    CHEMISTRY = "chemistry"
    SPACE_OBSERVATION_UV = "space-observation-uv"
    SPACE_SUPERCOMPUTING_4 = "space-supercomputing-4"
    HARD_RECYCLING = "hard-recycling"
    NEXUS = "nexus"
    SMELTING = "smelting"
    SPACE_MECHANICAL = "space-mechanical"
    CENTRIFUGING = "centrifuging"
    DELIVERY_CANNON = "delivery-cannon"
    CRAFTING = "crafting"
    SPACE_DECONTAMINATION = "space-decontamination"
    SPACE_THERMODYNAMICS = "space-thermodynamics"
    HAND_HARD_RECYCLING = "hand-hard-recycling"
    SPACE_GENETICS = "space-genetics"
    SPACE_SUPERCOMPUTING_3 = "space-supercomputing-3"
    SPACE_OBSERVATION_RADIO = "space-observation-radio"
    SPACE_COLLIDER = "space-collider"
    SPACE_CRAFTING = "space-crafting"
    BASIC_CRAFTING = "basic-crafting"
    ARCOSPHERE = "arcosphere"
    SPACE_GRAVIMETRICS = "space-gravimetrics"
    SE_ELECTRIC_BOILING = "se-electric-boiling"
    FUEL_REFINING = "fuel-refining"
    FUEL_PROCESSING = "fuel-processing"
    SPACE_ELECTROMAGNETICS = "space-electromagnetics"
    SPACE_ACCELERATOR = "space-accelerator"
    SPACE_RADIATOR = "space-radiator"


class CategoriesMapping(EnumMappingJson):
    __element_type__ = Category